#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          DNSCrypt
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Manages dnscrypt-proxy
# Description:       This file created using `dnscrypt-install' automate
#                    script. See:
#                    https://github.com/aidin36/dnscrypt-install
### END INIT INFO

# Author: Aidin Gharibnavaz <aidin@aidinhut.com>
#

DESC="Manages dnscrypt-proxy"
DAEMON="/usr/local/sbin/dnscrypt-proxy"
PIDFILE="/var/run/dnscrypt-proxy.pid"

case "$1" in
start) log_daemon_msg "Starting dnscrypt-proxy"
       $DAEMON --daemonize --ephemeral-keys --local-address="127.0.0.2:10053" --resolver-name="adamas" --pidfile=$PIDFILE
       log_daemon_msg $?
       ;;
stop) log_daemon_msg "Stopping dnscrypt-proxy"
      kill `cat $PIDFILE`
      log_daemon_msg $?
      ;;
restart) log_daemon_msg "Restarting dnscrypt-proxy"
        $0 stop
        $0 start
        ;;
esac
exit 0
